@startuml
actor user
participant backend
database datastore

user -> backend:Launch commander script
backend -> datastore:insert record
datastore -> backend:record inserted
backend -> datastore:update record
datastore -> backend:record updated
backend -> datastore:delete record
datastore -> backend:record deleted
backend -> datastore:select record
datastore -> backend:select row returned
backend -> user:Show record details
user -> backend:Launch password apply script
backend -> user:password success msg on cluster
backend -> user:password success on msg repo
backend -> user:password failure msg on cluster
backend -> user:password failure on msg repo


@enduml